{{- if .Values.pump.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pump-conf-{{ include "tyk-pump.fullname" . }}
  labels:
    app: pump-{{ include "tyk-pump.fullname" . }}
    chart: {{ include "tyk-pump.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- (.Files.Glob "configs/pump.conf").AsConfig | nindent 2 }}
{{- end }}
